### ISSUE TITLE
项目所有功能实现了吗?

### ISSUE THREAD

**Issue by shenxiang216** [Longgererer/JS-Encoder#18]
### 按一下回车代码就会执行一次

**Comment by Longgererer** [comment]
因为JS Encoder会使用防抖机制监听编辑窗口中的文本变化，在一定时间之后自动执行(默认500ms)，所以会出现你说的这种情况。

你可以在设置中取消自动执行的勾选，或者延长延迟执行的时间来减少代码执行的频率。

![1632305147(1)](https://user-images.githubusercontent.com/40834209/134324619-5ccccb0e-f1d6-4dbe-b5df-3f108c7be080.jpg)

**Comment by shenxiang216** [comment]
ok.项目非常棒，期待不断push

**Comment by Longgererer** [comment]
谢谢支持，我会继续努力😁
